use "rec.sml";
val file = TextIO.openIn "hw2given/tests/input/input04";
(*
recognizeToken file;
read_token file;
*)

recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;
recognizeToken file;

