#!/bin/csh -f
# test one and do diff

set b = `basename ${2} .df`
set dir = `dirname ${2}`

sml >&! ${dir}/${b}.tmp << END
val devnull = Posix.FileSys.openf ("/dev/null", Posix.FileSys.O_WRONLY, Posix.FileSys.O.trunc);
val sout = Posix.IO.dup(Posix.FileSys.stdout);
Posix.IO.dup2 {old=devnull, new=Posix.FileSys.stdout};
use "${1}";
Posix.IO.dup2 {old=sout, new=Posix.FileSys.stdout};
printAST (parse "${dir}/${b}.df");
END
grep -v "GC #" ${dir}/${b}.tmp | grep -v "Standard ML" | grep -v "autoloading" | grep -v "val " | grep -v "basis" | grep -v '^- $' >&! ${dir}/${b}.output
rm ${dir}/${b}.tmp

sml >&! ${dir}/${b}.tmp << END
val devnull = Posix.FileSys.openf ("/dev/null", Posix.FileSys.O_WRONLY, Posix.FileSys.O.trunc);
val sout = Posix.IO.dup(Posix.FileSys.stdout);
Posix.IO.dup2 {old=devnull, new=Posix.FileSys.stdout};
use "${1}";
Posix.IO.dup2 {old=sout, new=Posix.FileSys.stdout};
printAST (parse "${dir}/${b}.output");
END
grep -v "GC #" ${dir}/${b}.tmp | grep -v "Standard ML" | grep -v "autoloading" | grep -v "val " | grep -v "basis" | grep -v '^- $' >&! ${dir}/${b}.second
rm ${dir}/${b}.tmp

diff $dir/$b.output $dir/$b.second
diff $dir/$b.correct $dir/$b.second
rm $dir/$b.output
rm $dir/$b.second
